### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by samuelbeek** [popuparchive/audiosearch-client-node#1]
Hi, 

First of all; great work, I love your product. 
You should add this package to npm. It's more of a struggle now to set it up. 
[Here's how you can do it](https://docs.npmjs.com/getting-started/publishing-npm-packages). I can do it for you if you want?

**Comment by baileyspace** [comment]
Thanks @samuelbeek :) You should be able to find the audiosearch client on npm `npm i audiosearch-client-node` https://www.npmjs.com/package/audiosearch-client-node. Please let us know if you have any trouble with the installation.

**Comment by samuelbeek** [comment]
Thanks @baileyspace

**Comment by mgiraldo** [comment]
did you remove it from npm?

**Comment by samuelbeek** [comment]
@mgiraldo it is still visible: https://www.npmjs.com/package/audiosearch-client-node they don't have a readme file tough, so that's my you might be confused

**Comment by mgiraldo** [comment]
well, i get a `npm ERR! 404  'audiosearch-client-node' is not in the npm registry.` error when trying `npm i audiosearch-client-node`

 ¯\_(ツ)_/¯
